site_name: GRAIL Documentation
pages:
- Home: index.md
- Getting Started: gettingstarted.md
- Register: register.md
- Documentation: documentation.md
- Linkage process: linkage.md
- Criteria Description: criteria.md
- About: about.md

repo_url: https://github.com/digitalmusiclab/grail_api.git
site_author: Michael Barone
theme: readthedocs
